name: diffmet-py311
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.2.1
  - pytorch-cuda=12.1
  - lightning=2.2.1
  - torchmetrics==1.3.2
  - jsonargparse=4.27.7
  - uproot=5.3.1
  - vector=1.3.0
  - matplotlib=3.8.3
  - mplhep=0.3.41
  - scienceplots=2.1.1
  - pandas=2.2.1
  - statsmodels=0.14.1
  - hist=2.7.3
  - pdfcombine=1.1.5
  - pip
  - pip:
    - tensordict==0.3.1
    - typeshed-client>=2.1.0
